spring.application.name=notificacion
server.port=${PORT:8088}
# ===================================
# PostgreSQL + Hibernate (JPA) - NeonTech
# ===================================

spring.datasource.url=jdbc:postgresql://ep-icy-tree-aphvnfy6-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_KvDBYk9S8drA

# Configuracion de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
